identified = ['Yes','No']
discussprevious = ['Yes','No']
discowork = ['Yes','No']
discemploy = ['Yes','No']
sought = ['Yes','No']
bff = [0,1,2,3,4,5,6,7,8,9,10]
handled=['Yes, I experienced', 'Yes, I observed', 'Maybe/Not sure', 'No', "I've always been self-employed"]
wilcow=['No, at none of my previous employers','At some of my previous employers', 'Choosed not to fill','Yes, at all of my previous employers','Some of my previous employers']
formal =['Some did', 'None did', 'Choosed not to fill', "I don't know",'Yes, they all did']
seekhelp=['Some did', 'None did', 'Choosed not to fill', 'Yes, they all did']
fami=['No', 'Yes', "I don't know"]
curemploy=['No', "I don't know", 'Choosed not to fill', 'Yes']
past=['Possibly', 'Yes', 'No', 'Choosed not to fill', "Don't Know"]
ilfil=['No', 'Yes', 'Maybe', 'Choosed not to fill']
anon=["I don't know", 'Yes', 'Choosed not to fill', 'No']
anonprev=['Yes, always', "I don't know", 'Choosed not to fill', 'Sometimes','No']
gender=['Female', 'Male', 'Other']
iview=['Yes', 'Maybe', 'No']
interview=['Yes', 'Maybe', 'No']
comfy=['Same level of comfort for each', 'Choosed not to fill','Physical health', 'Mental health']
spv=['Yes, all of my previous supervisors','No, none of my previous supervisors', 'Choosed not to fill','Some of my previous supervisors', "I don't know"]
comforttalk=['Physical health', 'Choosed not to fill','Same level of comfort for each', 'Mental health']
inter=['Sometimes', 'Often', 'Not applicable to me', 'Rarely', 'Never']
age=['Between 25-30', 'Between 31-35', 'Between 36-40','Less than 25yo', 'Above 50', 'Between 41-50']
rtypes = ['Condominium', 'Apartment', 'Serviced Residence',
       'Terrace/Link House', 'Townhouse', 'Flat', 'Semi-detached House',
       'Bungalow']